# docker-compose -f docker-compose-mysql.yml up -d
# docker-compose -p belajar-golang -f docker-compose-mysql.yml up -d

version: '3'
services:
  mysql:
    container_name: belajar-golang
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'dbbelajar'
      MYSQL_USER: 'belajargolang'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - database-net
    volumes:
      - ./data:/var/lib/mysql

  adminer:
    container_name: adminer-container
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - database-net

networks:
  database-net:
